os:
  - linux

language: go

go:
  - "tip"
  - "1.10"

sudo: required

services:
  - docker

script:
  - make analysis
  - make coverage
  - make dev-test-e2e
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
